config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index]
  get 'icon_slot', to: "users#show_icon_modal"
  post 'change_slot', to: "users#change_slot"

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'rankings', to: 'users#rankings'

  resources :articles
  get 'tsviewer', to: 'articles#tsViewer'

  get 'store', to: "items#store"
  get 'inventory', to: 'items#inventory'
  post 'buy', to: "items#buy"
  post 'use', to: "items#use"
  get 'store_item', to: "items#store_item_modal"
  get 'inventory_item', to: "items#inventory_item_modal"
  
  root 'articles#index'
  get 'wip', to: 'welcome#index'
end

app/models/article.rb
class Article < ApplicationRecord

    has_one_attached :cover
    has_rich_text :content

    validates :title,
        presence: true
    
    validates :author,
        presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :is_admin?, only: [:new, :edit, :update, :destroy, :create]

  include Pagy::Backend

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @author = User.find(@article.author).username
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end

  def index
    @pagy, @articles = pagy(Article.all.reverse_order, items: 5)
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user.id
    @article.save
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :author, :cover)
  end

end

app/views/articles/edit.html.erb
<%= form_with model: @article, local: true, class: "news-new-form w-100 mb-5" do |f| %>
  <p class="page-title">Edit the New Article</p>

  <div class="form-group">  
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :article %>
    <%= f.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="form-group file-field">
    <%= f.label "Cover Picture" %>
    <%= f.file_field :cover, class: "form-control" %>
  </div>
  
  <%= f.submit class: "btn btn-primary" %>
  <%= link_to 'Back', article_path, class: "btn btn-secondary" %>
  
<% end %>

app/views/articles/index.html.erb
<div class="news-news-container flex-grow-1">
    
    <div class="d-flex justify-content-between">
        <div class="d-flex">
            <p class="page-title">NEWS</p>
            
            <% if user_signed_in? && current_user.admin? %>
                <%= link_to new_article_path, class: "btn btn-add-news shadow-none" do %>
                    <%= inline_svg_tag "svg/add.svg", class: "mb-2" %>
                <% end %>
            <% end %> 
        </div>

        <%= button_tag type: "button", class: "btn-tsviewer btn btn-sm btn-outline-light d-block d-sm-block d-md-none" do %>
            <%= link_to "TSVIEWER", tsviewer_path %>
        <% end %>
    </div>

    <% for article in @articles %>
    
        <!-- Article Card -->
        <%= link_to article_path(article), class: "article-card card border-0 rounded-0 shadow" do %>
           
            <% if article.cover.attached? %>
                <%= image_tag url_for(article.cover), class: "card-img-top rounded-0" %>
            <% end %>

            <div class="card-body d-flex align-items-center">
                <p class="article-title"><%=h article.title %></p>
                <p class="article-date ml-auto d-none d-sm-block d-md-none d-lg-block"><%= l article.created_at.to_date, format: :long %></p>
            </div>   
        
        <% end %>
    <% end %>
    <div class="d-flex justify-content-center">
        <%== render partial: 'pagy/bootstrap_nav', locals: {pagy: @pagy} %>
    </div>
</div>

<div id="ts3viewer_1086593" class="news-tsViewer-container d-none d-sm-none d-md-block shadow"></div>
<script src="https://static.tsviewer.com/short_expire/js/ts3viewer_loader.js"></script>
<%= javascript_pack_tag 'tsViewer' %>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, class: "news-new-form w-100 mb-5" do |f| %>
  <p class="page-title">Create A New Article</p>

  <div class="form-group">  
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :article %>
    <%= f.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="form-group file-field">
    <%= f.label "Cover Picture" %>
    <%= f.file_field :cover, class: "form-control" %>
  </div>
  
  <%= f.submit class: "btn btn-primary" %>
  
<% end %>

app/views/articles/show.html.erb
<% content_for :meta_title, @article.title %>

<div class="news-show-container d-flex flex-column w-100">

    <% if user_signed_in? && current_user.admin? %>
        <div class="toolbar-admin-article d-flex justify-content-end w-100">
                <%= link_to edit_article_path, class: "btn-edit-article" do %>
                    <% inline_svg_tag "svg/edit.svg" %>
                <% end %>
    
                <%= link_to article_path(@article),
                  class: "btn-edit-article",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } do %>
                    <% inline_svg_tag "svg/delete.svg" %>
                <% end %>
        </div>
    <% end %>

    <% if @article.cover.attached? %>
        <%= image_tag url_for(@article.cover), class: "cover" %>
        <% content_for :meta_image, url_for(@article.cover) %>
    <% end %>

    <%= content_tag :p, @article.created_at.strftime("%A %d.%m.%Y - %H:%M %p"), class: " mt-2" %>
    
    <div class="news-show-content">    
        <%= content_tag :p, @article.title, class: "article-title" %>
        <p class="article-content"><%= @article.content %></p>
    </div>
    
    <%= content_tag :p, "Author: #{@author}", class: "ml-auto mt-5 mb-5" %>    
</div>

<%= javascript_pack_tag 'link_blank' %>

app/views/articles/tsViewer.html.erb
<div id="ts3viewer_1086593" style="width: 200%;"></div>
<script src="https://static.tsviewer.com/short_expire/js/ts3viewer_loader.js"></script>
<%= javascript_pack_tag 'tsViewer' %>