config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index]
  get 'icon_slot', to: "users#show_icon_modal"
  post 'change_slot', to: "users#change_slot"

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'rankings', to: 'users#rankings'

  resources :articles
  get 'tsviewer', to: 'articles#tsViewer'

  get 'store', to: "items#store"
  get 'inventory', to: 'items#inventory'
  post 'buy', to: "items#buy"
  post 'use', to: "items#use"
  get 'store_item', to: "items#store_item_modal"
  get 'inventory_item', to: "items#inventory_item_modal"
  
  root 'articles#index'
  get 'wip', to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :inventories
  has_many :items, through: :inventories

  TS_IDENTITY_FORMAT = /\A
      (?=\A.{27}[=]) # Must contain 27 characters and end with '='
  /x

  has_one_attached :avatar
  
  validates :avatar, 
    content_type: [:png, :jpg, :jpeg], 
    size: { less_than: 256.kilobytes , message: 'is too big. Maximum size should be 256KB.' }

  validates :username, 
    presence: true, 
    uniqueness: true,
    :length => { :maximum => 14 }

  validates :ts_identity, 
    presence: true, 
    uniqueness: true,
    format: { with: TS_IDENTITY_FORMAT }

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  def update_icons
    @icons = Item.where(type: "Icon").pluck(:value)
    @currentIcons = Inventory.joins("INNER JOIN items ON inventories.item_id = items.id and inventories.user_id = #{self.id} and inventories.used = 1 and items.type = 'Slot'")

    begin
      ts = Teamspeak::Client.new("spacedose.de", "10011")
      ts.login('serveradmin', 'gFlQ9VUE')
      ts.command('use', sid: 1)
      id = ts.command('clientdbfind', {"pattern" => self.ts_identity}, '-uid').first["cldbid"]

      @groups = ts.command('servergroupsbyclientid', {"cldbid" => id})

      @groups.each do |t|
        if @icons.include?(t["sgid"]) then
          ts.command('servergroupdelclient', {"sgid" => t["sgid"], "cldbid" => id})
        end
      end
      
      @currentIcons.each do |t|
        if t.value != nil then
          ts.command('servergroupaddclient', {"sgid" => t.value, "cldbid" => id})
        end
      end

      ts.command('logout')
      ts.disconnect
      
      return true
    rescue StandardError => e
      puts e
      return false
    end
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_admin?, only: [:index, :destroy]
    before_action :authenticate_user!

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
        
        # Icons
        @slots = Inventory.joins("INNER JOIN items ON inventories.item_id = items.id and inventories.user_id = #{current_user.id} and inventories.used = 1 and items.type = 'Slot'")
        @iconNames = []

        @slots.each do |s|
            if s.value != nil then
                @iconNames.push(Item.where(type: "Icon").where(value: s.value).first.name)
            else
                @iconNames.push(Item.find(s.item_id).name)
            end
        end

        # Trophies
        @nothing = true
        # POI_total
        @poi_total = User.where(private: false).order("POI_total DESC").limit(3)
        # POI
        @poi = User.where(private: false).order("POI DESC").limit(3)
    end

    def show_icon_modal
        @unlockedIcons = Item.joins("INNER JOIN inventories ON inventories.item_id = items.id and inventories.user_id = #{current_user.id}").where("inventories.used = 1").where(type: "Icon")
        @slots = Item.joins("INNER JOIN inventories ON inventories.item_id = items.id and inventories.user_id = #{current_user.id}").where("inventories.used = 1").where(type: "Slot")

        respond_to do |format|
            format.js {render 'show_icon_modal'}
        end
    end

    def change_slot

        @slots = Inventory.joins("INNER JOIN items ON inventories.item_id = items.id and inventories.user_id = #{current_user.id} and inventories.used = 1 and items.type = 'Slot'")
        
        @slots.each_with_index do |slot, index|
            if params[:new_icon_id] != nil && params[:new_icon_id].length > index && params[:new_icon_id][index] != nil then
                slot.value = params[:new_icon_id][index]
            else
                slot.value = nil
            end
            slot.save
        end
        
        current_user.update_icons
        redirect_to user_path(current_user.id)
    end

    def rankings
        @poi_total = User.where(private: false).order("POI_total DESC")
        @poi = User.where(private: false).order("POI DESC")
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
    
        if @user.destroy
            redirect_to users_path, notice: "User deleted."
        end
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_ranking_table.html.erb
<p class="ranking-title"><%= title %></p>

<div class="trophies d-flex overflow-auto justify-content-between">    
    <%= link_to user_path(table.first.id) , class: "mx-5 mt-0 text-center d-flex flex-column align-items-center" do %>
        <%= inline_svg_tag "svg/cups/#{ image }.svg", class: "trophie-icon place-0" %>
        
        <div class="profile-picture">
            <% if table.first.avatar.attached? %>
                <%= image_tag url_for(table.first.avatar) %>
            <% else %>
                <%= image_tag "default_profile_pics/default-profile-pic.png", class: "profile-picture" %>
            <% end %>
        </div>
        
        <p class="trophie-title mb-3">
            <%= table.first.username %>
        </p>         
    <% end %>
    
    <%= link_to user_path(table.second.id), class: "mx-5 mt-3 text-center d-flex flex-column align-items-center" do %>
        <%= inline_svg_tag "svg/cups/#{ image }.svg", class: "trophie-icon place-1" %>
        
        <div class="profile-picture">
            <% if table.second.avatar.attached? %>
                <%= image_tag url_for(table.second.avatar) %>
            <% else %>
                <%= image_tag "default_profile_pics/default-profile-pic.png", class: "profile-picture" %>
            <% end %>
        </div>
        <p class="trophie-title mb-3">
            <%= table.second.username %>
        </p>
    <% end %>
 
    <%= link_to user_path(table.third.id), class: "mx-5 mt-4 text-center d-flex flex-column align-items-center" do %>
        <%= inline_svg_tag "svg/cups/#{ image }.svg", class: "trophie-icon place-2" %>
            
        <div class="profile-picture">
            <% if table.third.avatar.attached? %>
                <%= image_tag url_for(table.third.avatar) %>
            <% else %>
                <%= image_tag "default_profile_pics/default-profile-pic.png", class: "profile-picture" %>
            <% end %>
        </div>
   
        <p class="trophie-title mb-3">
            <%= table.third.username %>
        </p>
    <% end %>
</div>

<div class="trophies-forth d-inline-block mt-4 mb-5">
    <% table[3..-1].each_with_index do |user, index| %>
        <div class="d-inline-block mx-2 pb-3">
            <%= index + 4 %>.
            
            <%= link_to user_path(user.id), class: "profile-picture", data: { toggle: "popover", placement: "top", trigger: "hover", content: user.username} do %>
                <% if user.avatar.attached? %>
                    <%= image_tag url_for(user.avatar) %>
                <% else %>  
                    <%= image_tag "default_profile_pics/default-profile-pic.png", class: "profile-picture" %>
                <% end %>
            <% end %>
        </div>
    <% end %>
</div>
<hr class="mb-4"/>

app/views/users/_show_icon_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="iconModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center">
                <p class="modal-title page-title">Change Your Icons</p>
               
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <p>Select up to <b><%= @slots.length %></b> Icons:</p>

                <%= form_with url: change_slot_path, method: "post", id: "form-icon" do |f| %>
                    <% @unlockedIcons.each do |icon| %>
                        <div class="mb-2">
                            <%= image_tag "items/#{icon.name}.png", class: "mr-2" %>
                            <%= f.check_box :new_icon_id, {multiple: true}, icon.value, nil %>
                        </div>
                    <% end %>
                <% end %>
            </div>

            <div class="modal-footer">
                <%= button_tag "Save", type: "submit", form: "form-icon", class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/users/_trophie.html.erb
<% if table.include?(@user) %>
    <div class="mx-4">
        <% @nothing = false %>
        <%= inline_svg_tag "svg/cups/#{ image }.svg", class: "trophie-icon place-#{table.index(@user)}" %>
        <p class="trophie-title"><%= title %></p>
    </div>
<% end %>

app/views/users/index.html.erb
<div class="table-users w-100 h-100">
    <table class="table table-responsive-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">TS Unique ID</th>
                <th scope="col"></th>
            </tr>
        </thead>
        
        <tbody>
            <% for user in @users %>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= link_to user.username, user_path(user.id) %></td>
                    <td><%= user.ts_identity %></td>
                    <td>
                        <%= link_to admin_destroy_user_path(user.id), method: :delete, data: { confirm: "You sure?" }, class: "btn-delete-user" do %>
                            <% inline_svg_tag "svg/delete.svg" %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/rankings.html.erb
<div class="rankings-container d-flex flex-column w-100">
    <p class="page-title">RANKINGS</p>
    
    <%= render 'users/ranking_table', :table => @poi, :title => "Richest User", :image => "poi" %>
    <%= render 'users/ranking_table', :table => @poi_total, :title => "Most Time Wasted", :image => "poi_total" %>
</div>

<%= javascript_pack_tag 'rankings_positions' %>

app/views/users/show.html.erb
<div class="user-show-container container">
    <div class="profile-header mb-4 shadow">
        
        <% if @user.avatar.attached? %>
            <%= image_tag url_for(@user.avatar), class: "profile-picture" %>
        <% else %>
            <%= image_tag "default_profile_pics/default-profile-pic.png", class: "profile-picture" %>
        <% end %>

        <div class="container profile-content w-100 t-100">
            <div class="d-flex w-100">
                <%= content_tag :p, @user.username, class: "p-username mb-0 mr-3" %>
   
                <!-- IconSlots -->
                <% @iconNames.each do |item| %>
                    <div class="btn-link btn-icon-slot align-self-center mr-1">
                            <%= image_tag "items/#{item}.png" %>
                    </div>
                <% end %>

                <!-- Edit User -->
                <% if (current_user == @user) %> 
                    <div class="d-flex ml-auto">
                        <%= link_to icon_slot_path, class: "btn-edit-profile mr-2", remote: true do %>
                            <% inline_svg_tag "svg/change_icon.svg" %>
                        <% end %>
                        <%= link_to edit_user_registration_path, class: "btn-edit-profile mr-2" do %>
                            <% inline_svg_tag "svg/edit.svg" %>
                        <% end %>
                    </div>
                <% end %>
            </div>

            <p class="p-created-at">Member since <%= l @user.created_at.to_date, format: :long %></p>
            <% unless (current_user != @user) && @user.private %>
                <p class="p-poi mb-0">POI: <%= @user.POI %></p>
                <p class="p-poi mb-0">XP: <%= @user.POI_total %></p>
            <% else %>    
                <p class="mb-0 font-italic">profile is private</p>
            <% end %>    
        </div>
    </div>

    <% unless (current_user != @user) && @user.private %>

        <div class="profile-rankings mb-4 pb-1 shadow text-center">
            <div class="separator pt-1"><p class="page-title">Rankings</p></div>

            <div class="trophies d-flex overflow-auto">
                <%= render 'users/trophie', :table => @poi, :title => "Richest User", :image => "poi" %>
                <%= render 'users/trophie', :table => @poi_total, :title => "Most Time Wasted", :image => "poi_total" %>

                <% if @nothing %>
                    <% if (current_user == @user) %>              
                        <% if @user.private %> 
                            <p>Your profile is private. You can change your privacy settings <%= link_to "here", edit_user_registration_path %>.</p>
                        <% else %>             
                            <p>You currently have no trophies.</p>
                        <% end %>
                    <% else %>
                        <p>The user currently has no trophies.</p>
                    <% end %>
                <% end %>
            </div>
        </div>

    <% end %>

    <div id="iconModalDiv">
    </div>
</div>

app/views/users/show_icon_modal.js.erb
$("#iconModalDiv").html("<%= j render 'show_icon_modal' %>");
$("#iconModal").modal('show');