config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index]
  get 'icon_slot', to: "users#show_icon_modal"
  post 'change_slot', to: "users#change_slot"

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'rankings', to: 'users#rankings'

  resources :articles
  get 'tsviewer', to: 'articles#tsViewer'

  get 'store', to: "items#store"
  get 'inventory', to: 'items#inventory'
  post 'buy', to: "items#buy"
  post 'use', to: "items#use"
  get 'store_item', to: "items#store_item_modal"
  get 'inventory_item', to: "items#inventory_item_modal"
  
  root 'articles#index'
  get 'wip', to: 'welcome#index'
end

app/models/item.rb
class Item < ApplicationRecord

    require 'teamspeak-ruby'

    has_many :inventories
    has_many :users, through: :inventories

    def use (user)
        if (self.unique) then
            user.inventories.where(item_id: self.id, used: 0).first.update(used: 1)
        else
            user.inventories.where(item_id: self.id, used: 0).first.delete
        end

        return true
    end

    def get_flash_success
        return "Item used successfully"
    end

    def get_flash_error
        return "Something went wrong :("
    end        
end

app/models/items/icon.rb
class Icon < Item

    def use (user)
        super
    end

    def get_flash_success
        return "Icon Unlocked!"
    end

    def get_flash_error
        super
    end    
end

app/models/items/permission.rb
class Permission < Item

    def use (user)
        begin
            ts = Teamspeak::Client.new("spacedose.de", "10011")
            ts.login('serveradmin', 'gFlQ9VUE')
            ts.command('use', sid: 1)
            id = ts.command('clientdbfind', {"pattern" => user.ts_identity}, '-uid').first["cldbid"]
            ts.command('servergroupaddclient', {"sgid" => self.value, "cldbid" => id})
            ts.command('logout')
            ts.disconnect        
            super
        rescue StandardError => e
            puts e
            return false
        end
    end

    def get_flash_success
        return "Server Group Assigned!"
    end

    def get_flash_error
        return "TeamSpeak Server Error - Group Already Applied?"
    end    
end

app/models/items/slot.rb
class Slot < Item

    def use (user)
        super
    end

    def get_flash_success
        return "Slot Successfully Added!"
    end

    def get_flash_error
        super
    end    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!

    def index
    end

    def store
        @exclude = Item.joins("INNER JOIN inventories ON inventories.item_id = items.id and inventories.user_id = #{current_user.id}").where(unique: 1).ids
        @items = Item.where.not(id: @exclude)
        @alreadyBought = Item.where(id: @exclude)
    end

    def inventory
        @items = Item.joins("INNER JOIN inventories ON inventories.item_id = items.id and inventories.user_id = #{current_user.id}").where("inventories.used = 0")
        #@itemsUsed = Item.joins("INNER JOIN inventories ON inventories.item_id = items.id").where("inventories.used = 1", unique: 1)
    end

    def buy
        @item = Item.find(params[:item_id])

        if @item.price > current_user.POI then
            redirect_to store_path, notice: "You don't have enough POI :("
        else
            current_user.POI -= @item.price
            current_user.save
            current_user.items << @item
            flash[:success] = "Purchase Successful - Paid #{@item.price} POI."
            redirect_to store_path
        end 
    end

    def store_item_modal
        @item = Item.find_by_id(params[:item_id])

        respond_to do |format|
            format.js {render 'store_item_modal'}
        end
    end
    
    def inventory_item_modal
        @item = Item.find_by_id(params[:item_id])

        respond_to do |format|
            format.js {render 'inventory_item_modal'}
        end
    end

    def use
        @item = current_user.items.find(params[:item_id])

        if ( @item.use(current_user) ) then
            flash[:success] = @item.get_flash_success
        else
            flash[:error] = @item.get_flash_error
        end
        
        redirect_to inventory_path
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_inventory_item_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="itemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title page-title"><%= @item.name %> <%= @item.type %></p>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <%= @item.description %>
            </div>
        
            <div class="modal-footer">
                <%= link_to "Use", use_path(:item_id => @item.id), method: :post, class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/items/_store_item_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="itemModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title page-title"><%= @item.name %> <%= @item.type %></p>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </button>
            </div>
            
            <div class="modal-body">
                <%= @item.description %>
            </div>
        
            <div class="modal-footer">
                <%= link_to "Buy for #{@item.price}", buy_path(:item_id => @item.id), method: :post, class: "btn btn-primary" %>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/views/items/inventory.html.erb
<div class="items-inventory-container w-100 mb-5"> 
    <div class="d-flex justify-content-between">
        <p class="page-title">INVENTORY</p>
    </div>

    <% if @items.empty? then %>
        <p class="h5">You don't have any items yet. Go to the <%= link_to "Store", store_path %> and buy something!</p>
    <% end %>
    
    <div class="row">
        <% for item in @items.reverse do %>
            <div class="item-card col-lg-4 p-2">
                <%= link_to inventory_item_path(item_id: item.id), :class => "remove-link", remote: true do %>
                    <div class="d-flex flex-column align-items-center w-100 h-100 shadow">
                        <p class="item-title mt-2 mb-2"><%= item.type %></p>
                        <%= image_tag "items/#{item.name}.png" %>
                        <p class="item-title mt-1"><%= item.name %></p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>

    <div id="itemModalDiv">
    </div>
</div>

app/views/items/inventory_item_modal.js.erb
$("#itemModalDiv").html("<%= j render 'inventory_item_modal' %>");
$("#itemModal").modal('show');

app/views/items/store.html.erb
<div class="items-inventory-container w-100 mb-5"> 
    <div class="d-flex justify-content-between">
        <p class="page-title">STORE</p>
        <p class="page-title" style="font-style: normal">POI: <%= current_user.POI %></p>
    </div>

    <% if @items.empty? then %>
        <p class="h5">There is currently nothing for you to buy. Come back later.</p>
    <% end %>

    <div class="row">
        <% for item in @items do %>
            <div class="item-card col-lg-4 p-2">
                <%= link_to store_item_path(item_id: item.id), :class => "remove-link", remote: true do %>
                    <div class="d-flex flex-column align-items-center w-100 h-100 shadow">
                        <p class="item-title mt-2 mb-2"><%= item.type %></p>
                        <%= image_tag "items/#{item.name}.png" %>
                        <p class="item-title mt-1"><%= item.name %> (<%= item.price %>p)</p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>

    <div class="row mt-5">
        <% for item in @alreadyBought do %>
            <div class="item-card sold col-lg-4 p-2">
                <div class="d-flex flex-column align-items-center w-100 h-100 shadow">
                    <p class="item-title mt-2 mb-2"><%= item.type %></p>
                    <%= image_tag "items/#{item.name}.png" %>
                    <p class="item-title mt-1"><%= item.name %> (<%= item.price %>p)</p>
                    <%= image_tag "sold.png", class:"img-sold pb-4" %>
                </div>
            </div>
        <% end %>
    </div>

    <div id="itemModalDiv">
    </div>
</div>

app/views/items/store_item_modal.js.erb
$("#itemModalDiv").html("<%= j render 'store_item_modal' %>");
$("#itemModal").modal('show');