config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: [:show, :index]
  get 'icon_slot', to: "users#show_icon_modal"
  post 'change_slot', to: "users#change_slot"

  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'rankings', to: 'users#rankings'

  resources :articles
  get 'tsviewer', to: 'articles#tsViewer'

  get 'store', to: "items#store"
  get 'inventory', to: 'items#inventory'
  post 'buy', to: "items#buy"
  post 'use', to: "items#use"
  get 'store_item', to: "items#store_item_modal"
  get 'inventory_item', to: "items#inventory_item_modal"
  
  root 'articles#index'
  get 'wip', to: 'welcome#index'
end

app/views/layouts/_user_nav.html.erb
<nav class="navbar navbar-profile navbar-expand-lg navbar-dark d-flex justify-content-center">
    <ul class="navbar-nav w-100 justify-content-center flex-column">
    
        <li class="nav-item active">
            <%= link_to "PROFILE", user_path(current_user.id), class: "nav-link", method: "get" %>   
        </li>

        <li class="nav-item active">
            <%= link_to "INVENTORY", inventory_path, class: "nav-link", method: "get" %>   
        </li>
        
        <% if current_user.admin %>
            <li class="nav-item active">
                <%= link_to "USERS", users_path, class: "nav-link", method: "get" %>   
            </li>
        <% end %>

        <li class="nav-item active">
            <%= link_to "LOGOUT", destroy_user_session_path, class: "nav-link", method: "delete" %>   
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title><%= meta_title %></title>
    <meta property="og:image" content="<%= meta_image %>" />
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path("svg/spacedoselogo.svg") %>

  </head>

  <body>
    
    <div class="container-lg min-vh-100 d-flex flex-column">
      
      <!-- NavBar -->
      <nav class="navbar navbar-expand-lg navbar-dark align-items-center">
        <%= link_to articles_path, class: "navbar-brand d-flex" do %>
          <%= inline_svg_tag "svg/spacedoselogo.svg", class: 'brand-icon' %>
          <p class="align-self-center">SPACEDOSE.DE</p>
        <% end %>
        
        <!-- Hamburger Menu (Mobile) -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navigation Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          
          <ul class="navbar-nav ml-auto navbar-hide">
            <li class="nav-item active">
              <%= link_to "NEWS", articles_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><del>MEDIA</del></a>
            </li>
            <li class="nav-item active">
              <%= link_to "RANKING", rankings_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "STORE", store_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><del>TS5 PLUGIN</del></a>
            </li>
          </ul>

          <!-- Profile Picture -->
          <ul class="navbar-nav ml-auto">
            <li class="nav-item profile-picture">
              <div class="dropdown text-center">
                <%= link_to "", class: "btn-profile-dropdown #{'link-disable' if (controller_name == 'sessions' && action_name == 'new')}", role: "button", data: {toggle: "dropdown"} do %>

                  <% if user_signed_in? && current_user.avatar.attached? %> 
                    <%= image_tag url_for(current_user.avatar) %>
                  <% else %>
                    <%= image_tag "default_profile_pics/#{rand(6)}.png" %>
                  <% end %>

                  <%= inline_svg_tag "svg/profile_picture_border.svg", class: "profile-picture-border #{user_signed_in? ? 'online' : 'offline'}" %>
                  <% unless user_signed_in? %>
                    <%= inline_svg_tag "svg/profile_picture_sign_in.svg", class: "profile-picture-sign-in" %>
                  <% end %>
                <% end %>

                <div class="dropdown-menu dropdown-menu-right">
                  <% unless user_signed_in? %>
                    <%= render 'devise/sessions/new' %>
                  <% else %>
                    <%= render 'layouts/user_nav' %>
                  <% end %>
                </div>

              </div>
            </li>
          </ul>

        </div>
      </nav>

      <!-- Flash Message 
      <% flash.each do |type, msg| %>
        <div class="alert alert-type">
          <%= msg %>
        </div>
      <% end %>
      -->
      <%= flash_messages %>

      <div class="content d-flex flex-grow-1">
        <%= yield %>
      </div>

    </div>

    <div class="footer d-flex justify-content-center">
      <div class="container w-100 d-flex justify-content-center">
        <%= inline_svg_tag "svg/spacedoselogo.svg", class: 'footer-logo align-self-center', size: "32px*32px" %>
      </div>
    </div>

  </body>
</html>